# -*- coding: utf-8 -*-
"""OASIS INTERNSHIP->BMI CALCULATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fRp3Wj_EEH4g8niXv77H9ZTwvjTdjFs
"""



"""**AICTE OASIS INFOBYTE SIP TASK- THE BMI CALCULATOR**"""

def Calculate_BMI(Weight, Height):
    return Weight / (Height ** 2)

def Classify_BMI(BMI):
    if BMI < 18.5:
        return """Underweight:- Time to grab a bite!
By maintaining a healthy weight, you lower your risk of developing serious health problems."""
    elif 18.5 <= BMI < 24.9:
        return """Normal weight:- Great shape
By maintaining a healthy weight, you lower your risk of developing serious health problems."""
    elif 25 <= BMI < 29.9:
        return """Overweight:- Time to run!
By maintaining a healthy weight, you lower your risk of developing serious health problems."""
    else:
        return """Obesity:- Time to run!
By maintaining a healthy weight, you lower your risk of developing serious health problems."""

def Get_Weight():
    while True:
        try:
            Weight = float(input("Enter your weight in kilograms:- "))
            if Weight > 0:
                return Weight
            else:
                print("Weight must be a positive number. Please try again.")
        except ValueError:
            print("Invalid input. Please enter a numeric value for weight.")

def Get_Height():
    while True:
        try:
            Height = float(input("Enter your height in meters:- "))
            if Height > 0:
                return Height
            else:
                print("Height must be a positive number. Please try again.")
        except ValueError:
            print("Invalid input. Please enter a numeric value for height.")

def main():
    print("Welcome to the BMI Calculator!")

    Weight = Get_Weight()
    Height = Get_Height()

    BMI = Calculate_BMI(Weight, Height)
    Category = Classify_BMI(BMI)

    print(f"Your BMI is: {BMI:.2f}")
    print(f"Your BMI category is: {Category}")

if __name__ == "__main__":
    main()

2